######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 26 21:03:45 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloworld.c
